name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' # Matches your project version

      - name: Publish .NET Core Project
        run: dotnet publish MusicTheoryTrainerBlazor/MusicTheoryTrainerBlazor.csproj -c Release -o release --nologo

      # This fixes the 404 error on refresh
      - name: Change index.html base-href
        run: sed -i 's/<base href="\/" \/>/<base href="\/music-theory-quiz\/" \/>/g' release/wwwroot/index.html

      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Upload to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release/wwwroot
          branch: gh-pages # This creates a special hidden branch for the website